# Generated by Django 5.2.17 on 2026-08-11 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('natural', '자연분만'), ('cesarean', '제왕절개')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('birth_order', models.PositiveSmallIntegerField(default=1)),
                ('older_child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('initial_feeding_type', models.CharField(choices=[('breast', '모유'), ('formula', '분유'), ('mixed', '혼합')], max_length=20)),
                ('initial_pain_area', models.CharField(blank=True, max_length=100)),
                ('recovery_location', models.CharField(blank=True, max_length=100)),
                ('partner_referral_consent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
