# Generated by Django 5.2.17 on 2026-08-12 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('natural', '자연분만'), ('cesarean', '제왕절개')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('birth_order', models.PositiveSmallIntegerField(default=1)),
                ('older_child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('initial_feeding_type', models.CharField(choices=[('breast', '모유'), ('formula', '분유'), ('mixed', '혼합')], max_length=20)),
                ('initial_pain_area', models.CharField(blank=True, max_length=100)),
                ('recovery_location', models.CharField(blank=True, max_length=100)),
                ('partner_referral_consent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('emotion', models.CharField(blank=True, choices=[('happy', '행복한'), ('angry', '화남'), ('low_energy', '에너지부족'), ('sad', '슬픈'), ('depressed', '우울한'), ('confused', '혼란스러운'), ('calm', '차분한'), ('moody', '변덕스러운'), ('irritated', '짜증나는'), ('worried', '걱정스러운'), ('active', '활동적인')], max_length=15, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_area', models.CharField(blank=True, max_length=100)),
                ('breastfeeding', models.CharField(blank=True, choices=[('breast', '모유'), ('formula', '분유'), ('mixed', '혼합')], max_length=20, null=True)),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('exercise', models.CharField(blank=True, max_length=255)),
                ('activity_level', models.CharField(blank=True, choices=[('low', '낮음'), ('normal', '보통'), ('high', '많음')], max_length=10, null=True)),
                ('diet', models.JSONField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('skin_self_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hair_loss_status', models.CharField(blank=True, choices=[('same', '평소와 같음'), ('slight', '약간 빠짐'), ('heavy', '많이 빠짐')], max_length=20, null=True)),
                ('skin_symptom_tags', models.JSONField(blank=True, null=True)),
                ('pelvic_floor_symptoms', models.JSONField(blank=True, null=True)),
                ('private_fields', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='care.episode')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_memos/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '처리중'), ('done', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_memos', to='care.dailylog')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('episode', 'log_date'), name='unique_episode_log_date'),
        ),
    ]
