# Generated by Django 5.2.17 on 2026-08-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('emotion', models.CharField(blank=True, choices=[('happy', '행복한'), ('angry', '화남'), ('low_energy', '에너지부족'), ('sad', '슬픈'), ('depressed', '우울한'), ('confused', '혼란스러운'), ('calm', '차분한'), ('moody', '변덕스러운'), ('irritated', '짜증나는'), ('worried', '걱정스러운'), ('active', '활동적인')], max_length=15, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_area', models.CharField(blank=True, max_length=100)),
                ('breastfeeding', models.CharField(blank=True, choices=[('breast', '모유'), ('formula', '분유'), ('mixed', '혼합')], max_length=20, null=True)),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('exercise', models.CharField(blank=True, max_length=255)),
                ('activity_level', models.CharField(blank=True, choices=[('low', '낮음'), ('normal', '보통'), ('high', '많음')], max_length=10, null=True)),
                ('diet', models.JSONField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('skin_self_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hair_loss_status', models.CharField(blank=True, choices=[('same', '평소와 같음'), ('slight', '약간 빠짐'), ('heavy', '많이 빠짐')], max_length=20, null=True)),
                ('skin_symptom_tags', models.JSONField(blank=True, null=True)),
                ('pelvic_floor_symptoms', models.JSONField(blank=True, null=True)),
                ('private_fields', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='care.episode')),
            ],
            options={
                'ordering': ['-log_date'],
                'constraints': [models.UniqueConstraint(fields=('episode', 'log_date'), name='unique_episode_log_date')],
            },
        ),
    ]
