# Generated by Django 5.2.17 on 2026-08-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('daily', '일간')], default='daily', max_length=10)),
                ('plan_date', models.DateField()),
                ('ai_summary', models.TextField(blank=True)),
                ('bottleneck', models.CharField(blank=True, max_length=255)),
                ('reasoning', models.TextField(blank=True)),
                ('tomorrow_goal', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='care.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_skip', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', '임시생성'), ('confirmed', '확정'), ('done', '완료')], default='draft', max_length=10)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to='groups.membership')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_todos', to='groups.membership')),
                ('recovery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='care.recoveryplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recoveryplan',
            constraint=models.UniqueConstraint(fields=('episode', 'plan_date'), name='unique_episode_plan_date'),
        ),
    ]
