# Generated by Django 5.2.17 on 2026-08-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_dailylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_memos/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '처리중'), ('done', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_memos', to='care.dailylog')),
            ],
        ),
    ]
