# Generated by Django 5.2.17 on 2026-08-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_recoveryplan_todo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='initial_pain_area',
            new_name='initial_pain_area_custom_text',
        ),
        migrations.AddField(
            model_name='episode',
            name='initial_pain_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
