# Generated by Django 5.2.17 on 2026-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_rename_initial_pain_area_episode_initial_pain_area_custom_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='activity_level',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='activity_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='breast_milk_amount',
            field=models.CharField(blank=True, choices=[('low', '적음'), ('normal', '보통'), ('high', '많음')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='breastfeeding_pain_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
