# Generated by Django 5.2.17 on 2026-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_remove_dailylog_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='skin_self_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '매우 좋음'), (2, '좋음'), (3, '약간의 트러블'), (4, '트러블 심함')], null=True),
        ),
    ]
