# Generated by Django 5.2.17 on 2026-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0005_alter_dailylog_skin_self_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="hidden_tracking_categories",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
