# Generated by Django 5.2.17 on 2026-08-12 17:32

import django.db.models.deletion
import groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invite_code', models.CharField(default=groups.models.generate_invite_code, max_length=20, unique=True)),
                ('invite_code_expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '산모(소유자)'), ('member', '보호자')], max_length=10)),
                ('relation', models.CharField(blank=True, max_length=20, null=True)),
                ('data_scope', models.CharField(choices=[('full', '전체 조회'), ('partial', '일부 조회')], default='full', max_length=20)),
                ('notification_frequency', models.CharField(choices=[('daily', '매일'), ('every_other_day', '격일'), ('off', '안 받음')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_cohabiting', models.BooleanField(default=False)),
                ('available_time', models.JSONField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
