# Generated by Django 5.2.17 on 2026-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="notification_frequency",
        ),
        migrations.AddField(
            model_name="membership",
            name="notify_family_todo_completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="notify_family_todo_incomplete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="notify_todo_created",
            field=models.BooleanField(default=True),
        ),
    ]
