# Generated by Django 6.1 on 2026-08-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="available_time",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="is_cohabiting",
            field=models.BooleanField(default=False),
        ),
    ]
