# Generated by Django 5.2.17 on 2026-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_remove_membership_notification_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="notify_own_todo_incomplete",
            field=models.BooleanField(default=True),
        ),
    ]
