# Generated by Django 5.2.17 on 2026-08-20 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_membership_notify_own_todo_incomplete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="owner_user",
            field=models.OneToOneField(
                db_column="owner_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
