# Generated by Django 5.2.17 on 2026-08-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostpartumStage",
            fields=[
                ("stage_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("stage_name", models.CharField(max_length=50)),
                ("week_start", models.PositiveSmallIntegerField()),
                ("week_end", models.PositiveSmallIntegerField()),
                ("goal", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "postpartum_stages",
                "ordering": ["week_start"],
            },
        ),
    ]
