# Generated by Django 5.2.17 on 2026-08-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("noti_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("todo_assigned", "할일 배정"),
                            ("daily_log_missing", "일일기록 미작성"),
                            ("recovery_plan_ready", "회복플랜 생성됨"),
                            ("invite_joined", "보호자 가입됨"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50, null=True)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=255)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        db_column="membership_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="groups.membership",
                    ),
                ),
            ],
            options={
                "db_table": "Notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
